=== Satisfactory-Clips-Archive/Community-Highlights-Archive-Data/data/highlights-meta/grouped-meta.schema.json
{
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"$id": "grouped-meta.schema.json",
	"type": "object",
	"required": [
		"1.0",
		"biomes",
		"bugs",
		"aesthetics",
		"jace",
		"team",
		"in-game things",
		"creatures",
		"things players build",
		"community events",
		"weather"
	],
	"properties": {
		"1.0": {
			"type": "object",
			"required": [
				"buildings"
			],
			"properties": {
				"buildings": {
					"$ref": "../data/highlights-meta.json#/definitions/highlightsMeta"
				}
			}
		},
		"biomes": {
			"type": "object",
			"required": [
				"ambiguity",
				"zones",
				"subzones"
			],
			"properties": {
				"ambiguity": {
					"$ref": "../data/highlights-meta.json#/definitions/highlightsMeta"
				},
				"zones": {
					"$ref": "../data/highlights-meta.json#/definitions/highlightsMeta"
				},
				"subzones": {
					"type": "object",
					"additionalProperties": {
						"$ref": "../data/highlights-meta.json#/definitions/highlightsMeta"
					}
				}
			}
		},
		"bugs": {
			"$ref": "../data/highlights-meta.json#/definitions/highlightsMeta"
		},
		"community events": {
			"$ref": "../data/highlights-meta.json#/definitions/highlightsMetaCommunityEvents"
		},
		"aesthetics": {
			"type": "object",
			"required": [
				"themes",
				"time of day",
				"other"
			],
			"properties": {
				"themes": {
					"$ref": "../data/highlights-meta.json#/definitions/highlightsMeta"
				},
				"time of day": {
					"$ref": "../data/highlights-meta.json#/definitions/highlightsMeta"
				},
				"other": {
					"$ref": "../data/highlights-meta.json#/definitions/highlightsMeta"
				}
			}
		},
		"jace": {
			"$ref": "../data/highlights-meta.json#/definitions/highlightsMeta"
		},
		"snutt": {
			"$ref": "../data/highlights-meta.json#/definitions/highlightsMeta"
		},
		"mikael": {
			"$ref": "../data/highlights-meta.json#/definitions/highlightsMeta"
		},
		"team": {
			"$ref": "../data/highlights-meta.json#/definitions/highlightsMeta"
		},
		"in-game things": {
			"type": "object",
			"required": [
				"buildings",
				"vehicles",
				"other"
			],
			"properties": {
				"buildings": {
					"$ref": "../data/highlights-meta.json#/definitions/highlightsMeta"
				},
				"vehicles": {
					"$ref": "../data/highlights-meta.json#/definitions/highlightsMeta"
				},
				"other": {
					"$ref": "../data/highlights-meta.json#/definitions/highlightsMeta"
				}
			}
		},
		"creatures": {
			"$ref": "../data/highlights-meta.json#/definitions/highlightsMeta"
		},
		"things players build": {
		},
		"weather": {
			"$ref": "../data/highlights-meta.json#/definitions/highlightsMeta"
		}
	},
	"additionalProperties": {
		"$ref": "../data/highlights-meta.json#/definitions/highlightsMeta"
	}
}

=== Satisfactory-Clips-Archive/Community-Highlights-Archive-Data/data/highlights-meta/grouped-meta.json
{
	"1.0": {
		"buildings": [
			"alien power augmenter",
			"converter",
			"portal",
			"project assembly",
			"quantum encoder"
		]
	},
	"biomes": {
		"ambiguity": [
			"uncertain location",
			"unknown location"
		],
		"canyons": [
			"desert canyons",
			"maze canyons",
			"the great canyon"
		],
		"zones": [
			"abyss cliffs",
			"blue crater",
			"cave",
			"crater lakes",
			"dune desert",
			"eastern dune forest",
			"grass fields",
			"jungle spires",
			"lake forest",
			"northern forest",
			"paradise island",
			"red bamboo fields",
			"red jungle",
			"rocky desert",
			"snaketree forest",
			"southern forest",
			"spire coast",
			"swamp",
			"titan forest",
			"western beaches",
			"western dune forest"
		],
		"subzones": {
			"dune desert": [
				"desert canyons",
				"desert mountain plateaus"
			],
			"eastern dune forest": [
				"coin tree forest"
			],
			"grass fields": [
				"grass fields arch",
				"grass fields crater"
			],
			"northern forest": [
				"green valley",
				"the gates of beugernath"
			],
			"rocky desert": [
				"green valley",
				"the gates of beugernath"
			],
			"spire coast": [
				"the gates of beugernath"
			],
			"swamp": [
				"swamp waterfall"
			],
			"western beaches": [
				"beach islands",
				"long beach"
			]
		}
	},
	"bugs": [
		"flying vehicles",
		"glitch"
	],
	"jace": [
		"jace mom would live here",
		"jace would break there",
		"jace would chill out with friends there",
		"jace would chill there",
		"jace would commute there",
		"jace would contemplate things there",
		"jace would cross this bridge",
		"jace would cruise there",
		"jace would drink there",
		"jace would eat that",
		"jace would eat there",
		"jace would get abducted there",
		"jace would holiday there",
		"jace would live there",
		"jace would look at art there",
		"jace would not live there",
		"jace would play dota2 there",
		"jace would scheme evil schemes here",
		"jace would skateboard there",
		"jace would stay there for the weekend",
		"jace would stay there overnight",
		"jace would study there",
		"jace would walk around there",
		"jace would work there",
		"robo jace"
	],
	"snutt": [
		"snutt would live there"
	],
	"mikael": [
		"mikael would live there"
	],
	"aesthetics": {
		"themes": [
			"architecture",
			"art",
			"cityscape",
			"clockpunk",
			"cyberpunk",
			"dieselpunk",
			"ficsmas",
			"final fantasy",
			"fog",
			"games",
			"glass",
			"gothic",
			"industrial",
			"interior",
			"lasagn",
			"manifold",
			"megafactory",
			"nature",
			"oil rig",
			"pixel art",
			"repetition",
			"skatepark",
			"spaghett",
			"steampunk",
			"temporary is never temporary",
			"underwater",
			"weatherwax"
		],
		"time of day": [
			"night time",
			"sunrise/sunset"
		],
		"other": [
			"fan art",
			"memes",
			"modded",
			"multiplayer",
			"photo mode filter",
			"reference images",
			"references to other franchises"
		]
	},
	"team": [
		"no team",
		"team beacon",
		"team berry",
		"team boombox",
		"team build gun",
		"team candy cane",
		"team chainsaw",
		"team cup",
		"team customizer",
		"team detonator",
		"team feet",
		"team golden cup",
		"team hands",
		"team hover pack",
		"team inhaler",
		"team mushroom",
		"team nobelisk",
		"team nut",
		"team object scanner",
		"team paintgun",
		"team parachute",
		"team rebar",
		"team rifle",
		"team snowballs",
		"team statue",
		"team xenobasher",
		"team xenozapper",
		"team zipline"
	],
	"in-game things": {
		"buildings": [
			"vent",
			"packager",
			"crafting bench",
			"geothermal",
			"equipment workshop",
			"foundry",
			"mam",
			"assembler",
			"awesome shop",
			"awesome sink",
			"blender",
			"blueprint designer",
			"lookout tower",
			"miner",
			"oil extractor",
			"particle accelerator",
			"radar tower",
			"resource extractor",
			"space elevator",
			"train station",
			"truck station",
			"jump pad",
			"manufacturer",
			"smelter",
			"constructor",
			"refinery",
			"water extractor",
			"biomass burner",
			"power tower"
		],
		"vehicles": [
			"cyber wagon",
			"drone",
			"explorer",
			"factory cart",
			"tractor",
			"train",
			"truck"
		],
		"other": [
			"barrier",
			"pillars",
			"power switch",
			"boombox",
			"catwalk",
			"railing",
			"frames",
			"beams",
			"belts",
			"death crate",
			"dismantle crate",
			"fireworks",
			"foundation patterns",
			"hub",
			"cables",
			"ladder",
			"lights",
			"mercer sphere",
			"nobelisk",
			"parachute",
			"personal crate",
			"pipes",
			"portable miner",
			"signs",
			"somersloop",
			"stairs",
			"train signals",
			"tubes",
			"user interface",
			"train tracks",
			"crash site",
			"jetpack",
			"blade runners"
		]
	},
	"creatures": [
		"arachnophobia mode",
		"bean",
		"bird",
		"flying crab",
		"hog",
		"lizard doggo",
		"manta",
		"power slug",
		"spitter",
		"stinger"
	],
	"things players build": [
		"bestagons",
		"boat",
		"bridge",
		"canals",
		"causeway",
		"chimney",
		"coal plant",
		"cooling tower",
		"crane",
		"dam",
		"drills",
		"fuel plant",
		"furniture",
		"garage",
		"gas station",
		"gondola",
		"house",
		"hypertube cannon",
		"lighthouse",
		"manta gate",
		"nuclear plant",
		"oil plant",
		"outpost",
		"parking lot",
		"power storage bank",
		"pyramid",
		"roads",
		"signs as lights",
		"spaceship",
		"statue gallery",
		"tower",
		"train spiral",
		"train station",
		"tunnel",
		"utility tower",
		"viaduct",
		"warehouse"
	],
	"weather": [
		"aurora",
		"rain",
		"snow"
	],
	"community events": [
		"coffee cup studios"
	]
}
