=== Satisfactory-Clips-Archive/Community-Highlights-Archive-Data/data/authors.schema.json
{
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"$id": "authors.schema.json",
	"type": "object",
	"required": [
		"unaliased",
		"aliased"
	],
	"additionalProperties": false,
	"properties": {
		"unaliased": {
			"type": "object",
			"additionalProperties": {
				"type": "string"
			}
		},
		"aliased": {
			"type": "object",
			"additionalProperties": {
				"type": "string"
			}
		},
		"has_youtube": {
			"type": "object",
			"additionalProperties": {
				"type": "string"
			}
		},
		"youtube_aliases": {
			"type": "object",
			"additionalProperties": {
				"type": "string"
			}
		}
	}
}

=== Satisfactory-Clips-Archive/Community-Highlights-Archive-Data/data/authors.json
{
	"unaliased": {
		"____Ronnie____": "a9b95650-2b1f-415a-bccc-2b329eb8fa4f",
		"__MaX__": "29ab605d-6628-4f75-b964-55dec5b36e85",
		"_BlueWing_": "93b0eb7e-e858-42ff-8e60-6b2ba4af6e83",
		"_Bluuub_": "725ba6f9-4ddc-48ae-8540-863af728588f",
		"_ChillieTB-Wafer": "9ae3c05d-0706-41b5-873b-ab151c8c9b43",
		"_chroot": "f4b91e3c-c615-4c12-8e71-c09800a9098b",
		"_DeadSlug_": "9662e548-97b3-4562-9272-c009d79724a6",
		"_dork_chops_": "a5b3659c-9bdd-4056-86cf-d8f7874b60e6",
		"_Dragonhart": "e18917b2-897f-4dab-b761-25e885171d12",
		"_itg": "9f860b64-5167-4057-8038-1bc42bd490e5",
		"_nova_tech_": "ebb08526-40a7-4358-b657-6a1d68210e74",
		"_Paddy404_": "129e5509-a570-415f-9741-c968033bd101",
		"_sendai_": "6869586a-cf2e-4601-bf76-aca2fbe29c2a",
		"_Sesadre": "90c21754-b7b8-48b9-ad3e-22da49659e64",
		"_Tech4Life_": "486656d5-73dc-4410-8c36-df869298bacd",
		"_Venus94": "9d467770-8a63-48cf-8f46-3216390cd1af",
		"-Ailyrr-": "e4911109-abaf-497d-abf2-d39ac985ccda",
		"-Aquatically-": "100ab573-d247-438a-b073-9af1abf3242f",
		"-Calydon-": "43035ef7-05e2-49fe-b786-4990cab6f812",
		"-Kirbeh-": "4f6dcb3e-1d74-43e1-b30c-895ba86cdd25",
		"-Major-Stryker-": "a0a26c4f-db5a-45ea-89cb-b07403a9d6b6",
		"-matchaa-": "60e4ae09-d91d-4f9f-bb3c-148f920bfcf5",
		"-Ochiniwa-": "76e5ace9-e39c-4591-9b13-214bcff6e997",
		"-Samathos-": "a76d5b13-8c7a-48ff-b645-93a6be000412",
		"00STAR0": "da3f987e-e5f1-44f9-8d1d-5c03a45b5468",
		"0LowLight0": "0a829216-483f-40b1-afdc-cf7cb98d5c92",
		"1699Chaos": "eb80a6df-8178-4fa6-a6e4-a700667e2f7b",
		"1TARS1": "3f83e1af-72a6-4634-97bb-406b8976c270",
		"1Th3Gentl3man": "7d042ef4-d93d-4712-bc21-60bc37dd6ccf",
		"1TmW1": "b1a28ba8-e958-4319-8a3d-8af61fa8199a",
		"2-AB-b": "e9c22243-2b70-4aac-a248-7c47ca45563d",
		"2Sweet": "d8595729-3124-406b-972a-722d29f415d6",
		"3ndCraft": "f8013ff9-1ecd-4f7b-bcb0-33d4a261eb61",
		"420greener": "7a34b27f-4eaf-4074-a080-0653a873846c",
		"420SampleTxt": "6f6c9a18-c5c4-48fe-810c-b840644405e8",
		"4y744": "d2fa1303-1ba3-4098-bf0f-529ffc52d082",
		"5150-5150": "00440b19-0fd8-4e64-8c8d-da1f93ab277e",
		"7thMonkey": "c535cac1-5f84-47c6-815c-76d9cf0ad013",
		"A_Gh0st": "51bf55d4-2ef5-4c27-be25-9527d4a1931e",
		"Aaronium123": "0c9fb69c-8198-4523-a081-7cc998103c13",
		"AbleRunnerEli": "a4566667-4946-4a9b-83d2-30499db4abd3",
		"AbsentMarker335": "328f928d-95c6-4ad5-ae63-e85308af5c5f",
		"AccomplishedFridge": "7134ab42-5378-47db-8e1e-9f1f20a941a6",
		"Acnoisbae": "a53a4fdf-267c-4c34-9dbf-f1aa169fc6d1",
		"Adam the Useless": "b5033213-0d19-4a67-9308-bfba994e1e7c",
		"adam089": "6992f956-557e-4edd-8761-ff52b4f45286",
		"adamsogm": "3d8298df-2031-4cef-99a5-213be4951b0d",
		"AdamTheUseless": "97bc885c-bfab-4600-add4-0803d77cae24",
		"AdmiralDanial": "bf533d28-9f41-42a2-9f13-650592fbe1d8",
		"Adrason": "e2430086-7c0e-4f11-abbb-942da85826db",
		"adso_sadso": "6b67e070-6c47-43ee-9fb7-538049df6e63",
		"ADumbChicken": "96530024-bb7c-4a7a-b694-7d9f8a1d069d",
		"Aeellron": "13203409-cdc0-4a94-880c-0d068fa9c44e",
		"Aemon 144": "938190f2-efae-49c7-aac9-eab9efe408a9",
		"Aemon144": "eabc0a3a-dbb9-49d2-ab75-29fc62519b20",
		"Aeoliran": "3955489d-59ac-4906-b5f3-d5cba057c0a7",
		"AetherBytes": "bbc29d15-fa6a-4b10-bbdd-a09c03902a9c",
		"Aetherirum_33": "2eb31053-57b0-4ad4-aa07-4e85a8f4392f",
		"aFlickerFromBeyond": "06b9e888-ba16-4bb5-87ac-496c8f8aa268",
		"AG3NTjoseph": "acc07de2-38ff-4a17-9f7f-95bca54f85e7",
		"Agador777": "fd0349f2-f86f-4f9d-a8f7-d4ad3076857d",
		"Agent 86": "3127d49d-8c60-4351-a30d-9df335cc7252",
		"Agent119": "b30a9fc1-aa84-4882-9a53-b62f0e8087a8",
		"AggidudeSA": "61136336-1c79-4467-8fe7-1948f7151024",
		"AK Aunty Kai": "0ce49c23-33dd-43a1-b361-0dc36fb19fab",
		"akanix42": "f4d326b3-903f-4883-ab18-b61f69b1e79b",
		"AKauntykai": "2765baef-9148-4182-8ded-8d1f286152d7",
		"Aker_svk": "08756c31-fbc8-4fa3-847d-bce49eeb16b3",
		"AL7AIR": "1811852c-a7ec-4ffa-96db-ddcd67f380cf",
		"Alarming_Sector3474": "f80e5b1e-8026-4715-8ee4-d0ff9ce9f8cf",
		"Albino_Captain": "c89399b4-72f0-4fd5-8501-ba7eae09bc11",
		"Aleg8r": "959ab8a6-05b1-44a2-90d7-2a48bcc60f87",
		"Alex Crish": "c75bbe2c-7776-4acc-bb84-d3e9206ff18c",
		"Alex88FR": "ddd040a8-c6bd-4c20-a74d-7dd80b3a5000",
		"alextestsatis": "5aba19f1-7217-4763-9e78-ea08a3de3234",
		"alicewhatnot": "fb817d77-1825-4622-8d45-9c6afb3a9220",
		"All_Mine": "0220373a-69b4-4928-9a85-561186145859",
		"Allan53": "0d2b3470-7f40-4ddc-bf36-482e9c1c90cd",
		"almine2": "14b61175-78cd-486e-ad44-1b92d107d22c",
		"Almine2": "4181b32d-76c2-4aa7-a6f5-04e5c9fc44e6",
		"Alonte825": "ea47d472-f292-49c2-92e6-4d5f2ee42787",
		"Alt-Ctrl": "ed6bfcd8-0e58-4a08-b1e2-85478f420ed8",
		"AltimateJay": "fee005ff-406b-49db-813f-76f00257d1cd",
		"Always Ally": "c0e014b3-24e3-4942-89d7-4c4364b41310",
		"AmakoiX": "c7a3b40d-a7a8-43c1-a421-c309bdeac46a",
		"ambertalamasca": "3007fbb1-219a-4e70-8df4-aca6a19169dc",
		"ambrose_hy": "702ceb4b-4e83-4375-8002-a256f98b8e54",
		"Amelie of the Sea": "44e87869-213f-4315-a421-cb41935227ca",
		"amelieofthesea": "cf0c38de-a226-4ca9-8ab3-871f828bd924",
		"AmelieoftheSea": "862a96c3-5168-4e7d-8227-cfcff2e17500",
		"AmelieOfTheSea": "3f4e3f91-147b-4557-bbd7-baa8792d85f7",
		"AmePartyPirate": "a041971a-ab00-4603-990f-3a636651bcf7",
		"amthomsen": "99930367-6e1b-41d3-8fc0-6230a00477b9",
		"anarchyofana": "a92bedee-c898-4f73-903e-316bbbd6cdde",
		"AndersBlidberg": "8b9c6f86-b4d4-4cb3-840e-71044eba7406",
		"Andromeda_53": "86e30b17-c692-4186-b97a-395f9619cdd6",
		"andyrakov": "a55f19c5-059b-4689-b15a-fa850c5e1275",
		"anelegantskull": "ab8ed0d8-dd8a-4ad0-a0b3-81b2f18f195d",
		"ANGR1ST": "1d7bad4f-84f6-4a5d-80d3-ee19765ee8f3",
		"AngryKarpador": "ebbe0fb3-a732-40b6-a733-b9c9cf48a64d",
		"AnnaBanana322": "1ce9ea03-d780-4584-8dd9-da0785a42a15",
		"AnnaRooma": "cdb432d5-771f-4b9e-b08e-254a036b06cf",
		"AnnoraxKrenim": "8d80be5d-30cf-469b-902e-0f9ff297ad0f",
		"annoyingone": "4b43d442-3e71-4d10-b143-dd207f458f1f",
		"anOldVideoGamer": "8a7ea5a5-0bf2-40fd-be77-cae2e4e95706",
		"another-stolen-name": "24758447-f0d2-4c82-84a3-41a4fd9f940e",
		"AnotherPhilosopher": "c21f868a-65a9-40d1-b4e3-32707ec4444b",
		"AnthorNet": "27519564-0882-4515-a17b-474deecb36a3",
		"aphaits": "443d78a0-6d8c-4bdd-aa6f-699f8592a298",
		"Appalachisms": "b1d1e25f-a1b1-4a0e-96c1-469a6b565fb1",
		"Apprehensive_Ask7466": "a4d15a15-1808-4fe5-8fbc-63bdeb1f670d",
		"AproxPlays": "9cf6f2a3-5ec5-4f97-8e4a-ada926e889e2",
		"aq0437": "37750c55-5c13-468b-a9fa-15ec96cb82a5",
		"araldon": "d1b8368c-151a-4b3b-abc3-d6a7ee666706",
		"aramun_": "d9d540d2-d2d4-4a31-b0a8-fa6acb4effde",
		"Arbitation": "f9f3df08-31cd-4620-801d-678e1db5c2cc",
		"arblane": "c804de5f-b88e-4329-a655-a462a541672d",
		"arblanettv": "32fc8926-b53f-454d-8c5a-d651adea882b",
		"Arch_Mii": "937e7cd9-7a97-4667-a264-ac2c377db3df",
		"Archerymaister": "bf3476a4-49ce-4960-9a6b-23d3513a1b40",
		"Argasphere": "adda15a6-1153-4bf1-9151-72461919ddb0",
		"Arkyris": "1cd09200-b558-4e2e-9fb0-d39fa89e22a2",
		"arminrigo": "b5ba7107-3e1c-4577-a7b4-5af29c5f2916",
		"arnihilator": "196204f7-9e1e-4d49-bf38-bed5727ca5e2",
		"ARowe_gaming": "ded6189e-55b9-4b0d-89c0-39a41ebb3a87",
		"Art0212": "dc5d54c4-c513-48f1-8fc7-3bf00f704434",
		"Arteshi": "5c402af1-ab30-47ea-8c99-950a8fcfceba",
		"Ash_is_my_name": "08b1bb3c-6ef2-4994-8914-5dc043ad4f32",
		"aston209": "d76e1855-2b19-43a9-a4ce-1921695ce680",
		"Atexmplar": "f11cf41f-ea0c-4c49-be13-f06e83884da7",
		"Athrax": "8cecb3a8-d041-46f9-8d54-5dfbc580a885",
		"AubriTheHuman": "0f7b3dc2-f02b-440b-9336-f21d2236eb7c",
		"Audrey Plays Nice": "025cf34c-c150-4e1c-989e-ee18e34f3a0b",
		"AudreyPlaysNice": "be1694f5-14f9-42d4-86b5-232455b91f97",
		"audreyplaysnice2086": "739a8b79-1c86-420e-b8f4-278f389d65d7",
		"AuroraChrono": "1d0617c1-eacb-4903-bc1f-e619a529a12e",
		"auroragracett": "5e89fb11-55f2-44f0-bfd4-e0f9af0f8fda",
		"aushilfsgott": "c60b78ae-0ca6-4b94-817c-4f0eeedce8d5",
		"AustinLA88": "ac557d2b-b5c8-41f3-8e6f-34d173473f42",
		"Autism--_--": "c0bbef48-ad91-4a6b-9c49-1860f217628b",
		"Available_Cry8404": "6e0fa75e-261a-40d9-b9b8-ada2dd497d27",
		"avarageone": "ca7f8c9d-361a-4799-969a-0bdc3ad60ae3",
		"avionpassion": "40c8578f-cbf2-4e30-90ae-6e23f4a9d255",
		"Axe-of-Kindness": "b54d42ba-74d8-4841-b5c8-51405cb1d1e7",
		"AxeellYoung": "4af83353-7cbd-4ec6-8c2f-7a20fb8f24b5",
		"Axial_c44": "ba046710-0a89-45f6-8e09-73fc81a24366",
		"AxialC44": "c70947c3-dd44-42ef-b317-2c69e0e4501a",
		"AyrA_ch": "f9b77640-de24-4ba1-9e44-e6b03950d198",
		"B_ullseye": "e53d1378-e784-40bf-942f-80d70d728aca",
		"B00kw0rm01": "25183023-625f-4860-8978-531af76bb9c1",
		"BackThatThangUp": "6d55d7cd-9fb0-4197-841e-3d44887b9812",
		"BAD_Rants": "77a22afc-3a9b-46b1-a4ef-835c2c76017e",
		"Badmajic": "984dacb8-26c1-4feb-a0ba-e6ce6b896370",
		"Badv00doo": "f08372c4-5b3d-4d44-aec9-287c05838eb2",
		"Bahgtru": "d1531e80-6ff2-4395-a066-0b9afa9d3471",
		"baikenbits": "a15fffff-a5cd-4f1c-8795-3007178e58b0",
		"Baikenbits": "a9200200-e763-4c9f-834f-ca7e8ecb8fc7",
		"bajoly7": "219ff794-3802-4c80-9e55-3808a101a7ea",
		"baldfalk2": "b01e2ef5-e13e-4202-9d51-34fb46392f22",
		"BaldurFi": "9edbcfd5-f634-4e49-8901-166974dedfc8",
		"balls_are_fat2": "586f6295-acde-464b-877d-0c80d3d4ed94",
		"BambiGamerFr": "fe498e18-ef3f-4e7d-93cb-cea7ef5fd562",
		"BambiGamerFR": "09f73e81-0286-4ec0-bdf1-457f9aa420d5",
		"BananaReff": "c7af8993-154f-4c29-890b-b299b543efa9",
		"Basil_zazel": "8c02d661-3eca-43bc-9a2e-6fb9342dedd3",
		"bassbear": "c00cc0c3-635a-4b1d-a732-9458cb7b40d8",
		"BATT1": "18793f24-7c3e-4d60-8378-2903b005727c",
		"bdeguigne": "d53650a7-aab9-4090-9bdb-9b1cc2cda729",
		"beaker73_nl": "89e5be53-225d-4140-80b9-d802640ee628",
		"Beastlordius": "cac3916e-b9a5-441b-92ca-1bfc6ab25df1",
		"BEDplaysGAMES": "c4627a61-7250-4a59-a862-a0e22ec1f69b",
		"Beerfester": "ada8a259-e557-4003-afa4-9a5c6253d307",
		"Beijox_Gaming": "26717192-47a9-4771-abed-e689da3a2d96",
		"belindis": "a9d02424-dada-49aa-90e9-5f14131eaf68",
		"Ben_qoo": "9d1fa00a-9827-4a48-ae60-5e7d3ac06991",
		"BenderFondue": "ebe28749-3f75-4da6-a98d-f3e711010c23",
